### ISSUE TITLE
java.lang.NoSuchFieldError: No field Fill of type Landroidx/compose/ui/graphics/PaintingStyle

### ISSUE THREAD

**Issue by Javicompi** [tehras/charts#27]
App compiles, but crashes when tries to show the LineChart. I updated Compose version to 1.0.4, and still get it. 

java.lang.NoSuchFieldError: No field Stroke of type Landroidx/compose/ui/graphics/PaintingStyle; in class Landroidx/compose/ui/graphics/PaintingStyle; or its superclasses (declaration of 'androidx.compose.ui.graphics.PaintingStyle' appears in /data/app/~~1IClg3K24qqTN_iqrjdXRg==/es.jnsoft.whatweath-pLHYJOTf4GaonKm_ukZsTg==/base.apk)
        at com.github.tehras.charts.line.renderer.line.SolidLineDrawer.<init>(SolidLineDrawer.kt:14)
        at com.github.tehras.charts.line.renderer.line.SolidLineDrawer.<init>(Unknown Source:0)
        at com.github.tehras.charts.line.renderer.line.SolidLineDrawer.<init>(SolidLineDrawer.kt:8)

**Comment by ociler** [comment]
Did you find any solution? I have the same issue,

**Comment by Javicompi** [comment]
I didn't. Just implemented it on my own. Not as difficult as I thought in Compose.

**Comment by ociler** [comment]
Could you help me on this? I don't even know how to start  :'(

**Comment by Javicompi** [comment]
What I did was to adapt what I found in this article:

https://proandroiddev.com/building-your-first-custom-chart-in-android-with-jetpack-compose-a890fb60878b

I didn't need something too fancy anyway.

**Comment by ociler** [comment]
Yes, I checked that article too. I will try something like that. Thank you so much!!

**Comment by Javicompi** [comment]
Go for it. Might seem complicated. But as I said, with Compose is not that difficult.
